// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzebXHJP_4HYTAtso6Vp3tyOd1ALvH30w',
    appId: '1:592878237589:web:79b6535899b1e95db4a89c',
    messagingSenderId: '592878237589',
    projectId: 'australia-talk',
    authDomain: 'australia-talk.firebaseapp.com',
    storageBucket: 'australia-talk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD59GIhnJUB9-eYX5eA8EJc52YLLVzlS3Q',
    appId: '1:592878237589:android:8f5f13bd9d60ba03b4a89c',
    messagingSenderId: '592878237589',
    projectId: 'australia-talk',
    storageBucket: 'australia-talk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABGdW5lH_7vRMdY7fVip2E15NgjYZEXGg',
    appId: '1:592878237589:ios:67d1efa129575c20b4a89c',
    messagingSenderId: '592878237589',
    projectId: 'australia-talk',
    storageBucket: 'australia-talk.firebasestorage.app',
    iosBundleId: 'com.example.talkAmiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABGdW5lH_7vRMdY7fVip2E15NgjYZEXGg',
    appId: '1:592878237589:ios:67d1efa129575c20b4a89c',
    messagingSenderId: '592878237589',
    projectId: 'australia-talk',
    storageBucket: 'australia-talk.firebasestorage.app',
    iosBundleId: 'com.example.talkAmiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzebXHJP_4HYTAtso6Vp3tyOd1ALvH30w',
    appId: '1:592878237589:web:0f363cd2d28a7627b4a89c',
    messagingSenderId: '592878237589',
    projectId: 'australia-talk',
    authDomain: 'australia-talk.firebaseapp.com',
    storageBucket: 'australia-talk.firebasestorage.app',
  );
}
